sudo: required

services:
  - docker

script:
  - docker build -t $DOCKER_USERNAME/mytravis:latest .
  - docker images
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
  - docker push $DOCKER_USERNAME/mytravis:latest
